name: yossarian
favicon: null
layout_spectrum: 0.9406059409957379
typography_spectrum: 0.5579430446960032
title: Test
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.45642471918836236
  lightness: 0.3346422901377082
  saturation: 0.013171226950362325
  rhythmicContrast: 0.7183041253592819
purpose: []
